PersonJobBuilder
typedef PersonJobBuilder PersonJobBuilder::Self
PersonJobBuilder::PersonJobBuilder(Person &person)
Self& PersonJobBuilder::at(std::string company_name)
References Person::company_name, PersonBuilderBase::person.
Referenced by main__.
Self& PersonJobBuilder::as_a(std::string position)
References PersonBuilderBase::person, Person::position.
Referenced by main__.
Self& PersonJobBuilder::earning(int annual_income)
References Person::annual_income, PersonBuilderBase::person.
Referenced by main__.