Rectangle
int Rectangle::width
Referenced by setWidth.
int Rectangle::height
Referenced by setHeigth.
Rectangle::Rectangle(int width, int height)
virtual int Rectangle::getWidth() const
Referenced by process.
virtual void Rectangle::setWidth(int width)
References width.
virtual int Rectangle::getHeight() const
virtual void Rectangle::setHeigth(int height)
References height.
Referenced by process.
virtual int Rectangle::area() const
Referenced by process.