PersonAddressBuilder
typedef PersonAddressBuilder PersonAddressBuilder::Self
PersonAddressBuilder::PersonAddressBuilder(Person &person)
Self& PersonAddressBuilder::at(std::string street_address)
References PersonBuilderBase::person, Person::street_address.
Referenced by main__.
Self& PersonAddressBuilder::with_postcode(std::string post_code)
References PersonBuilderBase::person, Person::post_code.
Referenced by main__.
Self& PersonAddressBuilder::in(std::string city)
References Person::city, PersonBuilderBase::person.
Referenced by main__.